name: Bug Report
description: There is a Bug / Unexpected Behavior in the plugin
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        _Before reporting:_ Search for existing issues, read the readme thoroughly

  - type: checkboxes
    attributes:
      label: Notice taken
      options:
        - label: "I followed the instructions above before opening this issue"
          required: true

  - type: input
    attributes:
      label: "Discord Version"
      description: "Which Discord version are you using? (Under Settings in the bottom left corner)"
      placeholder: "i.e. 0.0.16"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Discord Release Channel"
      description: "Which Discord release channel are you using? (Under Settings in the bottom left corner)"
      options:
        - ptb
        - canary
        - stable
    validations:
      required: true

  - type: input
    attributes:
      label: "BetterDiscord Version"
      description: "Which BetterDiscord version are you using? (Under Settings in the bottom left corner)"
      placeholder: "i.e. 1.2.4"
    validations:
      required: true

  - type: input
    attributes:
      label: "Plugin Version"
      description: "Which Plugin version are you using? (Under Settings>Plugins>Animated Status)"
      placeholder: "i.e. 0.13.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Please describe in detail, what you expected to happen"

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "Please describe in detail, what actually happened and how to reproduce the bug"
