name: I Need Help
description: I need help working with the plugin / something does not work as anticipated
labels: [help wanted]
body:
  - type: markdown
    attributes:
      value: "_Before reporting:_ Search for existing issues, **read the readme thoroughly**"

  - type: checkboxes
    attributes:
      label: Notice taken
      options:
        - label: "I followed the instructions above before opening this issue"
          required: true

  - type: input
    attributes:
      label: "Plugin Version"
      description: "Which Plugin version are you using? (Under Settings>Plugins>Animated Status)"
      placeholder: "i.e. 0.13.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "What do you need help with?"
      description: "Please describe in detail, what you need help with"
